// "use client"
import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import Navbar from "~/components/Navbar";
import RecoilRootWrapper from "~/components/RecoilRootWrapper";
import PromotionalOffer from "~/components/PromotionalOffer";
import { RecoilRoot } from "recoil";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        {/* <RecoilRoot> */}
        <RecoilRootWrapper>
          <Navbar/>
          <PromotionalOffer/>
          {children}
        </RecoilRootWrapper>
        {/* </RecoilRoot> */}
        </body>
    </html>
  );
}
