export const userInterestsData=[
  "Photography",
  "Cooking",
  "Travel",
  "Music",
  "Reading",
  "Fitness",
  "Hiking",
  "Painting",
  "Writing",
  "Yoga",
  "Gardening",
  "Fashion",
  "DIY Projects",
  "Meditation",
  "Cycling",
  "Gaming",
  "Film Making",
  "Astronomy",
  "Knitting",
  "Dancing",
  "Calligraphy",
  "Woodworking",
  "Pottery",
  "Bird Watching",
  "Surfing",
  "Sailing",
  "Scuba Diving",
  "Skiing",
  "Snowboarding",
  "Mountain Climbing",
  "Archery",
  "Martial Arts",
  "Soccer",
  "Basketball",
  "Volleyball",
  "Tennis",
  "Golf",
  "Rugby",
  "Cricket",
  "Baseball",
  "Ice Hockey",
  "Table Tennis",
  "Chess",
  "Card Games",
  "Board Games",
  "Billiards",
  "Bowling",
  "Rock Climbing",
  "Canoeing",
  "Kayaking",
  "Fishing",
  "Horseback Riding",
  "Backpacking",
  "Camping",
  "Canyoning",
  "Bungee Jumping",
  "Skydiving",
  "Paragliding",
  "Windsurfing",
  "Kitesurfing",
  "Stand-up Paddleboarding",
  "Paintball",
  "Airsoft",
  "Laser Tag",
  "Go Karting",
  "Bouldering",
  "Parkour",
  "Skateboarding",
  "Rollerblading",
  "BMX",
  "Kiteboarding",
  "Wakeboarding",
  "Snowmobiling",
  "Jet Skiing",
  "White Water Rafting",
  "Ziplining",
  "Hot Air Ballooning",
  "Hang Gliding",
  "Ultralight Flying",
  "Mountain Biking",
  "Crossfit",
  "Kickboxing",
  "Taekwondo",
  "Judo",
  "Krav Maga",
  "Karate",
  "Fencing",
  "Badminton",
  "Polo",
  "Squash",
  "Racquetball",
  "Skate Skiing",
  "Biathlon",
  "Cross-country Skiing",
  "Speed Skating",
  "Figure Skating",
  "Ice Dancing",
  "Ice Climbing",
  "Ice Fishing",
  "Ice Sailing"
]
